language: java

install: mvn -U install --quiet -DskipTests=true
before_script:
   - "gem install travis-artifacts"
   - "mvn -version"
script: mvn install

after_failure:
  - "travis-artifacts upload --path ."

env:
 global:
   - "ARTIFACTS_AWS_REGION=us-east-1"
   - "ARTIFACTS_S3_BUCKET=drogus-artifacts"
   - secure: "JCQ1uz/rfrtMiUAvxeMznVB2wTX/f7lrCBa6oOsskDPt1dMzxD4aEuOfq3QlROLPDhYyu3dnWh1+ABla3Dx4+dCVA9ASgFCq5ivO5Vkxr4c6g8tb7hp14EitGEnWfEpdn64K6mZ7e7a/yjaXU3Ry4AisvPSk7wCcbHisBbj1LzE="
   - secure: "Dcya9JSXSa9qXDBXUihYxfCBL8VKCoIj5SQARMshYGLrs1zN2C4EcO4lcMkePTHWrGjpSqNdgnChUeg9YphWqODCcy2XhaMlSxwBYBDTye3hLGwKNdMKnrl/4yE+GoBg6Zaj9bB46Ua/GwLgZpOgM/b/VuCqnp6JC+hYOZKBhdg="
