language: java
services: mongodb

install: mvn install -q -U -DskipTests=true -Dmaven.test.redirectTestOutputToFile=true
script: mvn install -q -nsu -Dmaven.test.redirectTestOutputToFile=true -P '!integration'
