---
platform: linux
image_resource:
  type: registry-image
  source:
    repository: concourse/oci-build-task
    tag: 0.10.0
    registry_mirror:
      host: ((docker-hub-mirror))
      username: ((docker-hub-mirror-username))
      password: ((docker-hub-mirror-password))
inputs:
- name: ci-images-git-repo
outputs:
- name: image
caches:
- path: ci-image-cache
params:
  CONTEXT: ci-images-git-repo/ci/images
  DOCKERFILE: ci-images-git-repo/ci/images/((ci-image-name))/Dockerfile
  DOCKER_HUB_AUTH: ((docker-hub-auth))
  REGISTRY_MIRRORS: ((docker-hub-mirror))
run:
  path: /bin/sh
  args:
  - "-c"
  - |
    mkdir -p /root/.docker
    cat > /root/.docker/config.json <<EOF
    { "auths": { "https://index.docker.io/v1/": { "auth": "$DOCKER_HUB_AUTH" }}}
    EOF
    build
