---
platform: windows
inputs:
- name: git-repo
params:
  CI: true
  GRADLE_ENTERPRISE_CACHE_USERNAME:
  GRADLE_ENTERPRISE_CACHE_PASSWORD:
  GRADLE_ENTERPRISE_URL: https://ge.spring.io
run:
  path: git-repo/ci/scripts/build-project-windows.bat
