---
platform: linux
inputs:
- name: git-repo
- name: artifactory-repo
outputs:
- name: version
params:
  RELEASE_TYPE:
  ARTIFACTORY_SERVER:
  ARTIFACTORY_USERNAME:
  ARTIFACTORY_PASSWORD:
  BINTRAY_SUBJECT:
  BINTRAY_REPO:
run:
  path: git-repo/ci/scripts/promote.sh
