spring:
  security:
    saml2:
      relyingparty:
        registration:
          simplesamlphp:
            signing:
              credentials:
              - private-key-location: "classpath:saml/privatekey.txt"
                certificate-location: "classpath:saml/certificate.txt"
            identityprovider:
              verification:
                credentials:
                - certificate-location: "classpath:saml/certificate.txt"
              entity-id: simplesaml
              singlesignon:
                url: https://simplesaml-for-spring-saml/SSOService.php
          okta:
            signing:
              credentials:
              - private-key-location: "classpath:saml/privatekey.txt"
                certificate-location: "classpath:saml/certificate.txt"
            identityprovider:
              verification:
                credentials:
                - certificate-location: "classpath:saml/certificate.txt"
              entity-id: okta-id-1234
              singlesignon:
                url:
                  https://okta-for-spring/saml2/idp/SSOService.php
