spring:
  security:
    oauth2:
      authorizationserver:
        issuer: https://provider.com
        endpoint:
          authorization-uri: /authorize
          token-uri: /token
          jwk-set-uri: /jwks
          token-revocation-uri: /revoke
          token-introspection-uri: /introspect
          oidc:
            logout-uri: /logout
            client-registration-uri: /register
            user-info-uri: /user
        client:
          messaging-client:
            registration:
              client-id: messaging-client
              client-secret: "{noop}secret"
              client-authentication-methods:
                - client_secret_basic
              authorization-grant-types:
                - client_credentials
              scopes:
                - message.read
                - message.write
